import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./global_animation.css";
import AnimatedCursor from "react-animated-cursor"
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AnimatedCursor
          innerSize={14}
          outerSize={28}
          color="145, 26, 255"
          outerAlpha={0.2}
          innerScale={0.7}
          outerScale={5}
        />
        <NavBar />
        {children}  
        <Footer />
      </body>
    </html>
  );
}
